/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinamentosRouteImport } from './routes/treinamentos'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RedistribuicaoRouteImport } from './routes/redistribuicao'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksUteisRouteImport } from './routes/links-uteis'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as IntegracoesRouteImport } from './routes/integracoes'
import { Route as ImoveisRouteImport } from './routes/imoveis'
import { Route as FilasRouteImport } from './routes/filas'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'

const TreinamentosRoute = TreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RedistribuicaoRoute = RedistribuicaoRouteImport.update({
  id: '/redistribuicao',
  path: '/redistribuicao',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksUteisRoute = LinksUteisRouteImport.update({
  id: '/links-uteis',
  path: '/links-uteis',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegracoesRoute = IntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ImoveisRoute = ImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const FilasRoute = FilasRouteImport.update({
  id: '/filas',
  path: '/filas',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeadsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRoute
  '/dashboard': typeof DashboardRoute
  '/equipe': typeof EquipeRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/filas': typeof FilasRoute
  '/imoveis': typeof ImoveisRoute
  '/integracoes': typeof IntegracoesRoute
  '/leads': typeof LeadsRouteWithChildren
  '/links-uteis': typeof LinksUteisRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/redistribuicao': typeof RedistribuicaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/templates': typeof TemplatesRoute
  '/treinamentos': typeof TreinamentosRoute
  '/leads/$id': typeof LeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRoute
  '/dashboard': typeof DashboardRoute
  '/equipe': typeof EquipeRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/filas': typeof FilasRoute
  '/imoveis': typeof ImoveisRoute
  '/integracoes': typeof IntegracoesRoute
  '/leads': typeof LeadsRouteWithChildren
  '/links-uteis': typeof LinksUteisRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/redistribuicao': typeof RedistribuicaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/templates': typeof TemplatesRoute
  '/treinamentos': typeof TreinamentosRoute
  '/leads/$id': typeof LeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/conversas': typeof ConversasRoute
  '/dashboard': typeof DashboardRoute
  '/equipe': typeof EquipeRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/filas': typeof FilasRoute
  '/imoveis': typeof ImoveisRoute
  '/integracoes': typeof IntegracoesRoute
  '/leads': typeof LeadsRouteWithChildren
  '/links-uteis': typeof LinksUteisRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/redistribuicao': typeof RedistribuicaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/templates': typeof TemplatesRoute
  '/treinamentos': typeof TreinamentosRoute
  '/leads/$id': typeof LeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/equipe'
    | '/esqueci-senha'
    | '/filas'
    | '/imoveis'
    | '/integracoes'
    | '/leads'
    | '/links-uteis'
    | '/login'
    | '/redefinir-senha'
    | '/redistribuicao'
    | '/relatorios'
    | '/templates'
    | '/treinamentos'
    | '/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/equipe'
    | '/esqueci-senha'
    | '/filas'
    | '/imoveis'
    | '/integracoes'
    | '/leads'
    | '/links-uteis'
    | '/login'
    | '/redefinir-senha'
    | '/redistribuicao'
    | '/relatorios'
    | '/templates'
    | '/treinamentos'
    | '/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/clientes'
    | '/configuracoes'
    | '/conversas'
    | '/dashboard'
    | '/equipe'
    | '/esqueci-senha'
    | '/filas'
    | '/imoveis'
    | '/integracoes'
    | '/leads'
    | '/links-uteis'
    | '/login'
    | '/redefinir-senha'
    | '/redistribuicao'
    | '/relatorios'
    | '/templates'
    | '/treinamentos'
    | '/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CadastroRoute: typeof CadastroRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ConversasRoute: typeof ConversasRoute
  DashboardRoute: typeof DashboardRoute
  EquipeRoute: typeof EquipeRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  FilasRoute: typeof FilasRoute
  ImoveisRoute: typeof ImoveisRoute
  IntegracoesRoute: typeof IntegracoesRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LinksUteisRoute: typeof LinksUteisRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RedistribuicaoRoute: typeof RedistribuicaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TemplatesRoute: typeof TemplatesRoute
  TreinamentosRoute: typeof TreinamentosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinamentos': {
      id: '/treinamentos'
      path: '/treinamentos'
      fullPath: '/treinamentos'
      preLoaderRoute: typeof TreinamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redistribuicao': {
      id: '/redistribuicao'
      path: '/redistribuicao'
      fullPath: '/redistribuicao'
      preLoaderRoute: typeof RedistribuicaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links-uteis': {
      id: '/links-uteis'
      path: '/links-uteis'
      fullPath: '/links-uteis'
      preLoaderRoute: typeof LinksUteisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integracoes': {
      id: '/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof IntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imoveis': {
      id: '/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof ImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filas': {
      id: '/filas'
      path: '/filas'
      fullPath: '/filas'
      preLoaderRoute: typeof FilasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof LeadsRoute
    }
  }
}

interface LeadsRouteChildren {
  LeadsIdRoute: typeof LeadsIdRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsIdRoute: LeadsIdRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CadastroRoute: CadastroRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ConversasRoute: ConversasRoute,
  DashboardRoute: DashboardRoute,
  EquipeRoute: EquipeRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  FilasRoute: FilasRoute,
  ImoveisRoute: ImoveisRoute,
  IntegracoesRoute: IntegracoesRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LinksUteisRoute: LinksUteisRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RedistribuicaoRoute: RedistribuicaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  TemplatesRoute: TemplatesRoute,
  TreinamentosRoute: TreinamentosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
